# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)


phish_songs = [
"1999",
"46 Days",
"50 Ways to Leave Your Lover",
"5:15",
"99 Problems",
"99 Years",
"A Apolitical Blues",
"A Day in the Life",
"A Song I Heard The Ocean Sing",
"AC/DC Bag",
"Access Me",
"Acoustic Army",
"After Midnight",
"Ain't Love Funny",
"Aint Love Funny",
"Alaska",
"Albuquerque",
"All Along the Watchtower",
"All Blues",
"All Down The Line",
"All of These Dreams",
"All That You Dream",
"All The Pain Through The Years",
"All Things Reconsidered",
"Also Sprach Zarathustra",
"Alumni Blues",
"Amazing Grace",
"Amazing Grace Jam",
"Ambient Jam",
"Amoreena",
"Anarchy",
"Anarchy in the U.K.",
"And Your Little Dog Too",
"Another One Bites the Dust Jam",
"Any Colour You Like",
"Anything But Me",
"Aqui Como Alla",
"Architect",
"Army of One",
"Art Jam",
"Auld Lang Syne",
"Avenu Malkenu",
"Axilla",
"Axilla II",
"Baby Elephant Walk",
"Baby Lemonade",
"Babylon Baby",
"Back at the Chicken Shack",
"Back in the USSR",
"Back On The Train",
"Back Porch",
"Backwards Down The Number Line",
"Bass Duel",
"Bass Duo",
"Bathtub Gin",
"Beauty of a Broken Heart",
"Beauty of my Dreams",
"Been Caught Stealing",
"Bell Boy",
"Bertha",
"Big Alligator Song",
"Big Ball Jam",
"Big Balls",
"Big Black Furry Creature from Mars",
"Big Leg Emma",
"Big Pimpin'",
"Bike",
"Billy Breathes",
"Birds of a Feather",
"Birthday Jam",
"Bittersweet Motel",
"Black-Eyed Katy",
"Blackbird",
"Blank",
"Blister in the Sun",
"Blow Wind Blow",
"Blue and Lonesome",
"Blue Bayou",
"Blue Bossa",
"Blue Moon",
"Blue Skies",
"Blue Sky",
"Bluegrass Jam",
"Blues Jam",
"Bobby Jean",
"Bodhisattva Blues",
"Bohemian Rhapsody",
"Bold as Love",
"Boogie On Reggae Woman",
"Booty Ain't Nothing But a Butt Rap",
"Born to Run",
"Born Under Punches",
"Bouncing Around the Room",
"Bow Mt. Rag",
"Brain Damage",
"Brian and Robert",
"Brother",
"Brown Eyed Girl",
"Bruno",
"Buffalo Bill",
"Bug",
"Bundle of Joy",
"Bungalow Bill",
"Buried Alive",
"Burn That Bridge",
"Burning Down the House",
"Butter Them Biscuits",
"Bye Bye Foot",
"Call Me If You Ever Need A Fool",
"Camel Walk",
"Can't You Hear Me Knockin'",
"Cannonball",
"Cannonball Jam",
"Caravan",
"Carini",
"Carolina",
"Cars Trucks Buses",
"Casino Boogie",
"Cat Scratch Fever",
"Catapult",
"Cavern",
"Cecilia",
"Chalk Dust Torture",
"Champagne Supernova",
"Character Zero",
"Chariots of Fire",
"Che Hun Ta Mo",
"Chess Jam",
"Choo Choo Ch' Boogie",
"Cinnamon Girl",
"Cities",
"Clementine",
"Clod",
"Clone",
"Cold as Ice",
"Cold Rain and Snow",
"Cold Water",
"Colonel Forbin's Ascent",
"Come On (Let the Good Times Roll)",
"Come On Baby Lets Go Downtown",
"Come Together",
"Communication Breakdown",
"Contact",
"Cool it Down",
"Corinna",
"Corrina",
"Corrine Corrina",
"Costume Contest Jam",
"Cover of the Rolling Stone",
"Cowboy's Sweetheart",
"Cracklin' Rosie",
"Crew Football Theme Song",
"Crimes of the Mind",
"Crimson Jam",
"Crosseyed and Painless",
"Crossroads",
"Crowd Control",
"Cry Baby Cry",
"Cryin'",
"Cut My Hair",
"Daniel Saw the Stone",
"Dave's Energy Guide",
"David Bowie",
"Day Or Night",
"Dazed and Confused",
"Dear Mrs. Reagan",
"Dear Prudence",
"Demand",
"Destiny Unbound",
"Diamond Girl",
"Dickie Scotland",
"Digital Delay Loop Jam",
"Dinner and a Movie",
"Dirt",
"Discern",
"Dixie Cannonball",
"Dixie Chicken",
"Doctor Jimmy",
"Dog Faced Boy",
"Dog Log",
"Dogs Stole Things",
"Doin' My Time",
"Don't Bogart That Joint",
"Don't Get Me Wrong",
"Don't Pass Me By",
"Don't Want You No More",
"Don't You Wanna Go",
"Done Me Wrong",
"Donna Lee",
"Dooley",
"Down By the River",
"Down With Disease",
"Down With Disease Jam",
"Dr. Gabel",
"Drifting",
"Driver",
"Drowned",
"Drum Jam",
"Drums",
"Dust in the Wind",
"Earl's Breakdown",
"Easy To Slip",
"Eclipse",
"El Paso",
"Eliza",
"Emotional Rescue",
"Energy",
"Esther",
"Everybody's Got Something to Hide",
"Everybody's Got Something To Hide But Me and My Monkey",
"Everyday I Have The Blues",
"Eyes of the World",
"Faht",
"Family Picture",
"Farmhouse",
"Fast Enough For You",
"Fast Train",
"Fat Man In The Bathtub",
"Father Son Boogie",
"Feats Don't Fail Me Now",
"Fee",
"Feel Feel Feel The Heat",
"Feelin' Alright",
"Fikus",
"Final Flight",
"Fire",
"Fire on the Mountain",
"Fire up the Ganja",
"First Tube",
"Fixin' To Die",
"Flat Fee",
"Flip",
"Fluff's Travels",
"Fluffhead",
"Fly Famous Mockingbird",
"Fly Like an Eagle",
"Foam",
"Foreplay/Long Time",
"Four Strong Winds",
"Frankenstein",
"Frankie Says",
"Free",
"Free Man in Paris",
"Freebird",
"Freeworld",
"Friday",
"Frost",
"Fuck Your Face",
"Funky Bitch",
"Funny as it Seems",
"Gamehendge Time Factory",
"Garden Party",
"Gettin' Jiggy Wit It",
"Ghost",
"Ginseng Sullivan",
"Girls Girls Girls",
"Give Up the Funk(Tear the Roof Off the Sucker)",
"Glass Onion",
"Glide",
"Glide II",
"Gloria",
"Glory Days",
"Going Down Slow",
"Gold Soundz",
"Golden Age",
"Golden Lady",
"Golgi Apparatus",
"Gone",
"Good Night",
"Good Times Bad Times",
"Goodbye Jam",
"Got my Mojo Workin'",
"Gotta Jibboo",
"Grapevine",
"Grind",
"Guelah Papyrus",
"Gumbo",
"Guy Forget",
"Guyute",
"Gypsy Queen",
"Ha Ha Ha",
"Halfway to the Moon",
"Halley's Comet",
"Happiness is a Warm Gun",
"Happy Birthday",
"Happy Birthday Jam",
"Harpua",
"Harpua (reprise)",
"Harry Hood",
"Have Mercy",
"Head Held High",
"Heart and Soul",
"Heartbreaker",
"Heavy Things",
"Hello My Baby",
"Hello Skinny",
"Help Me",
"Help on the Way",
"Helpless",
"Helpless Dancer",
"Helter Skelter",
"Here Comes Sunshine",
"Hi-Heel Sneakers",
"Highway to Hell",
"Hold to a Dream",
"Hold Whatcha Got",
"Honey Pie",
"Hoochie Coochie Man",
"Horn",
"Houses in Motion",
"How High is the Moon",
"How High the Moon",
"Hurricane",
"HYHU",
"HYHU Jam",
"I am Hydrogen",
"I am the Sea",
"I Am The Walrus",
"I Been Around",
"I Been to Georgia on a Fast Train",
"I Can't Turn You Loose",
"I Didn't Know",
"I Don't Care",
"I Fooled Around and Fell in Love",
"I Found a Reason",
"I Get a Kick Out of You",
"I Heard It Through The Grapevine",
"I Just Want To See His Face",
"I Kissed A Girl",
"I Know a Little",
"I Shall be Released",
"I Told You So",
"I Walk the Line",
"I Wanna Be Like You",
"I Will",
"I Wish",
"I'll Come Running",
"I'm Blue I'm Lonesome",
"I'm Blue, I'm Lonesome",
"I'm Coming Home",
"I'm Gonna Be",
"I'm One",
"I'm So Tired",
"I've Had Enough",
"I've Turned Bad",
"Icculus",
"Icculus Jam",
"Idea",
"If I Could",
"If I Don't be There by Morning",
"If I Only Had a Brain",
"If You Need a Fool",
"In a Hole",
"In The Aeroplane Over The Sea",
"Indian War Dance",
"Instant Karma",
"Invisible",
"Iron Man",
"Is It In My Head",
"It's Ice",
"It's My Life",
"It's No Good Trying",
"Izabella",
"Jaegermeister",
"Jam",
"Jazz Interlude",
"Jennifer Dances",
"Jeopardy Theme",
"Jesus Just Left Chicago",
"Johnny B Goode",
"Join The Band",
"Joy",
"Julia",
"Julius",
"Jump Monk",
"Jumpin' Jack Flash",
"Jungle Boogie",
"Keyboard Army",
"Keyboard Jam",
"Kill Devil Falls",
"Killing in the Name",
"Kung",
"L.A. Woman",
"La Bamba Jam",
"La Grange",
"Lawn Boy",
"Layla",
"Legalize It",
"Lengthwise",
"Leprechaun",
"Let It Loose",
"Let Me Lie",
"Letter to Jimmy Page",
"Life is a T.V. Show",
"Life On Mars",
"Lifeboy",
"Light",
"Light Up or Leave Me Alone",
"Limb By Limb",
"Lion Sleeps Tonight",
"Listening Wind",
"Lit O Bit",
"Little Drummer Boy",
"Little Red Rooster",
"Lively Up Yourself",
"Lizards Jam",
"Llama",
"Lonesome Cowboy Bill",
"Long Cool Woman",
"Long Long Long",
"Look Out Cleveland",
"Loup Garou",
"Love Me",
"Love me Like a Man",
"Love Reign O'er Me",
"Love You",
"Loving Cup",
"Low Rider",
"Luke-a-Roo",
"Lushington",
"Magilla",
"Makisupa Policeman",
"Manteca",
"Martha My Dear",
"Maze",
"McGrupp and the Watchful Hosemasters",
"Mean Mr. Mustard",
"Meat",
"Meatstick",
"Mellow Mood",
"Melt the Guns",
"Memories",
"Mercenary Territory",
"Merry Pranksters' Bozo Madness",
"Messin' with the Kid",
"Messing With The Kid",
"Mexican Cousin",
"Mice and Bats",
"Mid-Highway Blues",
"Middle Of The Road",
"Midnight Hour",
"Midnight on the Highway",
"Midnight Rider Jam",
"Mighty Quinn (Quinn the Eskimo)",
"Mike's Song",
"Mind Left Body Jam",
"Minute by Minute",
"Mirror in the Bathroom",
"Miss You",
"Mist",
"Misty Mountain Hop",
"Moby Dick",
"Mock Song",
"Money",
"Monkey Man",
"Moonlight in Vermont",
"Moose the Mooche",
"Mother Nature's Son",
"Mound",
"Mountains in the Mist",
"Mozambique",
"Mr. Completely",
"Mr. P.C.",
"Mustang Sally",
"My Friend My Friend",
"My Generation",
"My Girl",
"My Left Toe",
"My Long Journey Home",
"My Mind's Got a Mind of its Own",
"My Problem Right There",
"My Soul",
"My Sweet One",
"Nellie Kane",
"Never",
"New Age",
"New York New York",
"NICU",
"Night Moves Jam",
"Night Nurse",
"Ninja Mike Rap",
"No Dogs Allowed",
"No Quarter",
"NO2",
"Not Fade Away",
"Nothing",
"Nowhere Fast",
"O Mio Babbino Caro",
"Ob La Di Ob La Da",
"Ob-La-Di Ob-La-Da",
"Ob-La-Di Ob-La-Da jam",
"Oblivious Fool",
"Ocelot",
"Ode to a Dream",
"Oh Atlanta",
"Oh! Sweet Nuthin'",
"Old Folks' Boogie",
"Old Home Place",
"On My Knees",
"On My Knees Reprise",
"On the Road Again",
"On the Run",
"On Your Way Down",
"Once in a Lifetime",
"One Meatball",
"Oye Como Va Jam",
"P. Funk (Wants to Get Funked Up)",
"Party Time",
"Paul and Silas",
"Peaches en Regalia",
"Pebbles and Marbles",
"Phase Dance",
"Phish's set was rained out",
"Piano Duet",
"Pig in a Pen",
"Piggies",
"Pigtail",
"Piper",
"Poor Heart",
"Possum",
"Prep School Hippie",
"Prince Caspian",
"Proud Mary",
"Psycho Killer",
"Punch Me In The Eye",
"Punch You in the Eye",
"Purple Rain",
"Quadrophenia",
"Quadrophonic Toppling",
"Ramble On",
"Rapper's Delight",
"Reba",
"Revival",
"Revolution",
"Revolution 1",
"Revolution 9",
"Rhinoceros",
"Rhymes",
"Ride Captain Ride",
"Rift",
"Riker's Mailbox",
"Ring of Fire Jam",
"Rip This Joint",
"Roadhouse Blues",
"Roadrunner",
"Rock and Roll",
"Rock and Roll all Night",
"Rock and Roll All Nite",
"Rock and Roll Part Two",
"Rock Me Baby",
"Rocket In My Pocket",
"Rocket Man",
"Rocko William",
"Rocks Off",
"Rocky Mountain Way",
"Rocky Raccoon",
"Rocky Top",
"Roggae",
"Roses are Free",
"Rotation Jam",
"Round Room",
"Run Like An Antelope",
"Run Like An Antelope Jam",
"Runaway Jim",
"Running with the Devil",
"Sabotage",
"Sad Lisa",
"Sailin' Shoes",
"Sample in a Jar",
"Samson Variation",
"Sand",
"Sanity",
"Satin Doll",
"Savoy Truffle",
"Saw it Again",
"Say Something",
"Scarlet Begonias",
"Scent of a Mule",
"Scents and Subtle Sounds",
"Sea and Sand",
"Secret Smile",
"Seen and Not Seen",
"Self",
"Setting Sail",
"Seven Below",
"Sexual Healing",
"Sexy Sadie",
"Shafty",
"Shaggy Dog",
"Shake Your Hips",
"She Caught the Katy",
"She Thinks I Still Care",
"She's Bitchin' Again",
"Shine",
"Shine A Light",
"Shortage",
"Show Of Life",
"Silent in the Morning",
"Simple",
"Sixteen Candles",
"Skin It Back",
"Skippy the Wondermouse",
"Slave to the Traffic Light",
"Sleep",
"Sleep Again",
"Sleeping Monkey",
"Slipknot",
"Smells Like Teen Spirit",
"Smoke on the Water",
"Sneaking Sally Through the Alley",
"So Lonely",
"Something",
"Something's Wrong With My Baby",
"Somewhere Over the Rainbow",
"Soul Shakedown Party",
"Soul Survivor",
"Space Jam",
"Spanish Flea",
"Spanish Moon",
"Sparkle",
"Sparks",
"Speak to Me/Breathe in the Air",
"Spices",
"Split Open and Melt",
"Spock's Brain",
"Spooky",
"Spread It Round",
"Squeeze Box",
"St. Thomas",
"Stairway to Heaven",
"Stand",
"Star Trek Jam",
"Star Trek Theme",
"Stash",
"Stay Tuned...",
"Stealing Time From The Faulty Plan",
"Steam",
"Steep",
"Stir it Up Jam",
"Stop Breaking Down",
"Strange Design",
"Sugar Shack",
"Summer of '89",
"Suskind Hotel",
"Suspicious Minds",
"Suzy Greenberg",
"Sweet Adeline",
"Sweet Baby's Arms",
"Sweet Black Angel",
"Sweet Emotion",
"Sweet Emotion Jam",
"Sweet Jane",
"Sweet Virginia",
"Swept Away",
"Swing Low",
"Swing Tune",
"Take Me to the River",
"Take the A-Train",
"Talk",
"Taste",
"Taste That Surrounds",
"Tears of a Clown",
"Tela",
"Tell Me Something Good",
"Tennessee Waltz",
"Tequila Jam",
"Terrapin",
"Terrapin Station",
"Thank You",
"That's Alright Mama",
"The Asse Festival",
"The Ballad of Curtis Loew",
"The Birdwatcher",
"The Chase",
"The Chicken",
"The Connection",
"The Curtain",
"The Curtain With",
"The Dirty Jobs",
"The Divided Sky",
"The Flintstones Theme",
"The Fog That Surrounds",
"The Gambler",
"The Great Curve",
"The Great Gig in the Sky",
"The Happy Whip and Dung Song",
"The Horse",
"The Inlaw Josie Wales",
"The Landlady",
"The Lizards",
"The Maker",
"The Man Who Stepped Into Yesterday",
"The Mango Song",
"The Moma Dance",
"The Oh Kee Pa Ceremony",
"The Other One",
"The Overload",
"The Pendulum",
"The Price of Love",
"The Prison Joke",
"The Punk and the Godfather",
"The Real Me",
"The Revolution's Over",
"The River",
"The Rock",
"The Rover",
"The Sloth",
"The Squirming Coil",
"The Star Spangled Banner",
"The Way It Goes",
"The Wedge",
"Them Changes",
"Theme from Andy Griffith",
"Theme from the Bottom",
"Three Little Birds",
"Thrill Is Gone",
"Thunder Road",
"Thunderhead",
"Tibetan monks chant",
"Timber (Jerry the Mule)",
"Time",
"Time Loves a Hero",
"Time Turns Elastic",
"Tomorrow's Song",
"Too Much of Everything",
"Torn and Frayed",
"Touch Me",
"Train Round the Bend",
"Train Song",
"Trenchtown Rock",
"Tripe Face Boogie",
"Tropical Hot Dog Night",
"Tube",
"Tube Jam",
"Tubthumping",
"Tuesday's Gone",
"Tumbling Dice",
"Turd On The Run",
"Tush",
"Tweezer",
"Tweezer Reprise",
"Twenty Years Later",
"Twist",
"Two Dollar Bill",
"Two Versions of Me",
"Uncle Pen",
"Uncloudy Day",
"Undermind",
"Undone",
"Unknown",
"Us and Them",
"Ventilator Blues",
"Vibration of Life",
"Viola Lee Blues",
"Vultures",
"Wading in the Velvet Sea",
"Wait",
"Waking Up",
"Walfredo",
"Walk Away",
"Walk This Way",
"Walls of the Cave",
"Waste",
"Water in the Sky",
"Waterloo Jam",
"Waves",
"We're an American Band",
"We're Not Gonna Take It",
"Weekapaug Groove",
"Weigh",
"West LA Fadeaway",
"What Things Seem",
"What's the Use",
"When Something is Wrong with My Baby",
"When The Cactus Is In Bloom",
"When the Circus Comes to Town",
"While My Guitar Gently Weeps",
"Whipping Post",
"White Rabbit Jam",
"Who by Fire",
"Who Do We Do",
"Who Knows",
"Who Loves the Sun",
"Whole Lotta Love",
"Why Don't We Do it in the Road",
"Why Don't You Love Me",
"Why Dont You Love Me?",
"Why You Been Gone so Long",
"Why You've Been Gone So Long",
"Wild Child",
"Wild Honey Pie",
"Wildwood Weed",
"Will It Go Round In Circles",
"Will the Circle Be Unbroken",
"Willin'",
"Wilson",
"Wind Beneath My Wings",
"Windora Bug",
"Windy City",
"Wipeout",
"Wolfman's Brother",
"Won't You Come Home Bill Bailey",
"Wonderful You",
"Woodstock",
"Worm Talk",
"Worm Town Jam",
"Y'rushalayim Shel Zahav",
"Ya Mar",
"Yarmouth Road",
"Yer Blues",
"You Ain't Going Nowhere",
"You Enjoy Myself",
"You Gotta See Mama Every Night",
"You Shook Me All Night Long",
"You're No Good"
]

secret_cove_songs = [
  "Hallway of Masters",
  "Triceratops",
  "Steps",
  "The Underground",
  "Alice",
  "Shades of Cottage Grove",
  "Strangers",
  "It Keeps on Being Tuesday",
  "The Banana Song",
  "C.L.A.M."
]

secret_cove = Artist.create(name: 'Secret Cove')

secret_cove_songs.each do |song_name|
  secret_cove.songs.find_or_create_by_name(song_name)
end